# This workflow installs node dependencies and runs npm start
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x' # Specify the Node.js version you want to use
    - run: npm install # Install all dependencies from package.json
      env:
        NODE_ENV: production # Optional: Set NODE_ENV if needed
    - run: npm start # Run the start script
